const USER_LOGIN = "USER_LOGIN";
const USER_LOGIN_LOADING = "USER_LOGIN_LOADING";
const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
const USER_LOGIN_FEILD = "USER_LOGIN_FEILD";
const USER_LOGOUTH = "USER_LOGOUTH";
const USER_LOGOUTH_SUCCESS = "USER_LOGOUTH_SUCCESS";

const USER_REGISTRATION = "USER_REGISTRATION";
const USER_REGISTRATION_LOADING = "USER_REGISTRATION_LOADING";
const USER_REGISTRATION_SUCCESS = "USER_REGISTRATION_SUCCESS";
const USER_REGISTRATION_FELID = "USER_REGISTRATION_FELID";
const CLEAR_REGISTRATION_STORE = "CLEAR_REGISTRATION_STORE";

const SEARCH_USER = "SEARCH_USER";
const SEARCH_USER_LOADING = "SEARCH_USER_LOADING";
const SEARCH_USER_SUCCESS = "SEARCH_USER_SUCCESS";
const SEARCH_USER_ERROR = "SEARCH_USER_ERROR";
const SEARCH_CLEAR_ACTION = "SEARCH_CLEAR_ACTION";

export {
  USER_LOGIN,
  USER_LOGIN_LOADING,
  USER_LOGIN_SUCCESS,
  USER_LOGIN_FEILD,
  USER_LOGOUTH,
  USER_LOGOUTH_SUCCESS,
  USER_REGISTRATION,
  USER_REGISTRATION_LOADING,
  USER_REGISTRATION_SUCCESS,
  USER_REGISTRATION_FELID,
  CLEAR_REGISTRATION_STORE,
  SEARCH_USER,
  SEARCH_USER_LOADING,
  SEARCH_USER_SUCCESS,
  SEARCH_USER_ERROR,
  SEARCH_CLEAR_ACTION
};
