const USER_LOGIN = "USER_LOGIN";
const USER_LOGIN_LOADING = "USER_LOGIN_LOADING";
const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
const USER_LOGIN_FEILD = "USER_LOGIN_FEILD";
const USER_LOGOUTH = "USER_LOGIN_FEILD";

const USER_REGISTRATION = "USER_REGISTRATION";
const USER_REGISTRATION_LOADING = "USER_REGISTRATION_LOADING";
const USER_REGISTRATION_SUCCESS = "USER_REGISTRATION_SUCCESS";
const USER_REGISTRATION_FELID = "USER_REGISTRATION_FELID";

export {

    USER_LOGIN,
    USER_LOGIN_LOADING,
    USER_LOGIN_SUCCESS,
    USER_LOGIN_FEILD,
    USER_LOGOUTH,

    USER_REGISTRATION,
    USER_REGISTRATION_LOADING,
    USER_REGISTRATION_SUCCESS,
    USER_REGISTRATION_FELID

};